# Generated by Django 4.2.7 on 2025-07-05 01:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='open', max_length=10)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
        ),
    ]
