name: Dependency Update

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Update Python dependencies
      run: |
        cd api
        pip install pip-tools
        pip-compile --upgrade requirements.in || echo "No requirements.in found"
        pip install -r requirements.txt
        pip list --outdated
        
    - name: Update Node.js dependencies
      run: |
        cd frontend
        npm update
        npm audit fix --force || echo "Audit fix failed"
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          This PR updates dependencies to their latest versions.
          
          ## Changes
          - Updated Python dependencies
          - Updated Node.js dependencies
          
          Please review and test before merging.
        branch: dependency-update
        delete-branch: true 